[package]
name = "rustuino"
authors = ["SebastianBraun01 <SebastianBraun-Ost@protonmail.com>"]
edition = "2018"
version = "0.1.0"

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.14"
rtt-target = "0.3.1"
panic-halt = "0.2.0"
heapless = "0.7.0"
libm = "0.2.1"
paste = "1.0.5"

[dependencies.stm32f4]
version = "0.13.0"
features = ["stm32f446", "rt"]

[lib]
name = "rustuino"
test = false
bench = false
